# Generated by Django 3.2.7 on 2021-09-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=8)),
                ('criterias', models.TextField(default='[]')),
            ],
        ),
    ]
